# rest
rest:
  address: ":1480"

# indexer
indexer:
  address: ":1481"
  host: "http://localhost"
  # token: "mysecret"
  endpoint: "http://localhost:1453"
  limiter:
    rate: 3
    duration: "1s"
  workers: 5
  timeout: "30s"

# store
store:
  path: "./tmp/"
