# rest
rest:
  address: ":1480"

# indexer
indexer:
  address: ":1481"
  host: "http://localhost"
  # endpoint: "wss://decoded.wtf/ws/"
  endpoint: "ws://decoded.wtf:1460"
  limiter:
    rate: 3
    duration: "1s"
  workers: 5
  timeout: "30s"

# store
store:
  path: "./tmp/"
