# rest
rest:
  address: ":1480"

# indexer
indexer:
  address: ":1481"
  host: "http://localhost"
  endpoint: "wss://eth-mainnet.g.alchemy.com/v2/6S77iu4XWkdCm3lztMIZql9JOLMW_adQ"
  limiter:
    rate: 3
    duration: "1s"
  workers: 5
  timeout: "30s"

# store
store:
  path: "./tmp/"
